version: "3"

services:
  db:
    image: postgres:15-alpine
    container_name: db_deploy
    restart: always
    tty: true
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste
    ports:
      - "5432:5432"
